receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging:
    # logLevel: debug

  file/traces:
    path: /log/otel/traces.log
  file/metrics:
    path: /log/otel/metrics.log
  file/logs:
    path: /log/otel/logs.log

  prometheus:
    endpoint: "0.0.0.0:8889"

  otlp:
    endpoint: "jaeger:4317"
    tls:
      insecure: true

  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"
    tls:
      insecure: true

  debug:
    verbosity: detailed

  otlp/elastic:
    # Elastic APM server https endpoint without the "https://" prefix
    endpoint: "http://apm-server:8200"
    tls:
      insecure: true
    # headers:
    #   # Elastic APM Server secret token
    # Authorization: "Bearer ${env:ELASTIC_APM_SECRET_TOKEN}"

processors:
  batch:

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

service:
  # extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug, otlp/elastic]
    metrics:
      receivers: [otlp]
      exporters: [debug, otlp/elastic]
    logs:
      receivers: [otlp]
      exporters: [debug, otlp/elastic]
