version: '3.4'

services:

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.93.0

  apm-server:
    image: docker.elastic.co/apm/apm-server:7.17.16
    # image: docker.elastic.co/apm/apm-server:8.11.4

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.16
    # image: docker.elastic.co/elasticsearch/elasticsearch:8.11.4

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.16
    # image: docker.elastic.co/kibana/kibana:8.11.4



  # prometheus:
  #   image: prom/prometheus:v2.49.1

  # jaeger:
  #   image: jaegertracing/all-in-one:1.53

  # grafana:
  #   image: grafana/grafana:10.3.1

  # loki:
  #  image: grafana/loki:2.9.4

  # promtail:
  #   image: grafana/promtail:2.9.4

  blazorapp:
    image: ${DOCKER_REGISTRY-}blazorapp
    build:
      context: .
      dockerfile: BlazorApp/Dockerfile

  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile

