version: '3.4'

services:
  prometheus:
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  jaeger:
    ports:
      - "16686:16686"
      - "4317:4317"
    environment:
      - LOG_LEVEL=debug
  #   networks:
  #     - jaeger-example
  # hotrod:
  #   image: jaegertracing/example-hotrod:${JAEGER_VERSION:-latest}
  #   # To run the latest trunk build, find the tag at Docker Hub and use the line below
  #   # https://hub.docker.com/r/jaegertracing/example-hotrod-snapshot/tags
  #   #image: jaegertracing/example-hotrod-snapshot:0ab8f2fcb12ff0d10830c1ee3bb52b745522db6c
  #   ports:
  #     - "8080:8080"
  #     - "8083:8083"
  #   command: ["all"]
  #   environment:
  #     - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4318
  #   networks:
  #     - jaeger-example
  #   depends_on:
  #     - jaeger

  grafana:
    ports:
      - "3000:3000"

  blazorapp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ASPNETCORE_HTTP_PORTS=80
      - ASPNETCORE_HTTPS_PORTS=81
    ports:
    - "8080:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
      - prometheus
      - jaeger

  webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ASPNETCORE_HTTP_PORTS=80
      - ASPNETCORE_HTTPS_PORTS=81
    ports:
    - "8081:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
      - prometheus
      - jaeger