version: '3.4'

services:

  prometheus:
    image: prom/prometheus:v2.49.1

  jaeger:
    image: jaegertracing/all-in-one:1.53

  grafana:
    image: grafana/grafana:10.3.1

  # loki:
  #   image: grafana/loki:2.9.4

  # promtail:
  #   image: grafana/promtail:2.9.4

  blazorapp:
    image: ${DOCKER_REGISTRY-}blazorapp
    build:
      context: .
      dockerfile: BlazorApp/Dockerfile

  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile

